name: Java CI/CD EcoMove avec SonarQube via Ngrok

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ecomove
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping -proot" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout du code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 

    - name: Configuration du JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Compilation et Tests
      run: ./mvnw clean verify
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:3306/ecomove
        SPRING_DATASOURCE_USERNAME: root
        SPRING_DATASOURCE_PASSWORD: root

    - name: Vérifier la connectivité SonarQube (Debug)
      run: |
        S_URL=$(echo "${{ secrets.SONAR_HOST_URL }}" | tr -d '\r\n' | xargs)
        echo "Vérification de l'URL : ${S_URL}"
        echo "--- VERSION ---"
        curl -s "${S_URL}/api/server/version"
        echo "--- TEST BOOTSTRAP INDEX ---"
        curl -i -s "${S_URL}/batch/index" | head -n 20
      continue-on-error: true

    - name: Analyse SonarQube
      run: |
        # Nettoyage automatique des secrets pour éviter les erreurs de formatage et les espaces
        S_URL=$(echo "${{ secrets.SONAR_HOST_URL }}" | tr -d '\r\n' | xargs)
        S_TOKEN=$(echo "${{ secrets.SONAR_TOKEN }}" | tr -d '\r\n' | xargs)
        
        ./mvnw sonar:sonar \
        -Dsonar.projectKey=EcoMove \
        -Dsonar.host.url="${S_URL}" \
        -Dsonar.token="${S_TOKEN}" \
        -Dsonar.qualitygate.wait=true

    - name: Sauvegarde de l'Artifact (JAR)
      uses: actions/upload-artifact@v4
      with:
        name: ecomove-app
        path: target/*.jar

    - name: Connexion Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build et Push de l'image Docker
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/ecomove:latest